name: Deploy to Staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to staging cluster
    steps:
      - run: |
          echo" ${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          mkdir .ssh
          echo "${{secrets.KNOWN_HOSTS}}" &> ~/.ssh/known_hosts
          ssh -i ~/ssh_key root@13.201.18.99
        #   cd week-25-ci-next-app/ && git pull
        #   pnpm install
        #   pnpm build
        #   pm2 restart fe-server
        #   pm2 restart http-server
        #   pm2 restart ws-server
